title: Ascend SMP
description: Minecraft SMP Website

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default

exclude:
  - ascend-plugin
  - serve.js
  - node_modules
  - Gemfile
  - Gemfile.lock
  - README.md
